# Generated by Django 6.0.4 on 2026-04-22 17:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'API Fetch')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('train_type', models.CharField(choices=[('AVE', 'AVE'), ('AV City', 'AV City'), ('ALVIA', 'ALVIA'), ('INTERCITY', 'INTERCITY'), ('EUROMED', 'EUROMED'), ('REGIONAL', 'REGIONAL'), ('MD-LD', 'MD-LD')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('train_class', models.CharField(max_length=50)),
                ('fare', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.datarun')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_trips', to='core.station')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_trips', to='core.station')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('origin', 'destination', 'start_date', 'end_date', 'train_type', 'fare', 'price')},
            },
        ),
    ]
