# Generated by Django 6.0.4 on 2026-04-22 18:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_time', models.DateTimeField()),
                ('collected_at', models.DateTimeField()),
                ('temperature_c', models.FloatField()),
                ('windspeed_kmh', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('winddirection_deg', models.IntegerField()),
                ('weathercode', models.IntegerField()),
                ('is_day', models.BooleanField()),
                ('source', models.CharField(choices=[('api', 'API Fetch')], default='api', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.city')),
                ('data_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.datarun')),
            ],
            options={
                'ordering': ['-api_time'],
                'unique_together': {('city', 'api_time')},
            },
        ),
    ]
