# Generated by Django 6.0.4 on 2026-04-22 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_weatherobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_date', models.DateField()),
                ('temperature_max_c', models.FloatField()),
                ('temperature_min_c', models.FloatField()),
                ('precipitation_sum_mm', models.FloatField()),
                ('windspeed_max_kmh', models.FloatField()),
                ('weathercode', models.IntegerField()),
                ('source', models.CharField(choices=[('api', 'API Fetch')], default='api', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_weather', to='core.city')),
                ('data_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.datarun')),
            ],
            options={
                'ordering': ['-weather_date'],
                'unique_together': {('city', 'weather_date')},
            },
        ),
    ]
