# Generated by Django 6.0.4 on 2026-04-23 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailyweather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyWeather',
        ),
    ]
